"""
Export utilities for generating JSON, CSV, Markdown, and interactive HTML threat reports.
"""

from __future__ import annotations
import csv
import io
import json
import html
from typing import List
from vulnhound.models import CVEItem


def to_json(items: List[CVEItem], indent: int = 2) -> str:
    """Serializes CVEItems into formatted JSON."""
    raw = [item.to_dict() for item in items]
    return json.dumps(raw, indent=indent, ensure_ascii=False)


def to_csv(items: List[CVEItem]) -> str:
    """Exports CVEItems into standard CSV format."""
    output = io.StringIO()
    writer = csv.writer(output)
    writer.writerow([
        "CVE ID",
        "CVSS Score",
        "Severity",
        "EPSS Score",
        "EPSS Percentile",
        "CISA KEV",
        "Has PoC",
        "Attack Vector",
        "Privileges Required",
        "Published Date",
        "CWE IDs",
        "Description",
    ])

    for item in items:
        writer.writerow([
            item.id,
            item.cvss_score if item.cvss_score is not None else "",
            item.severity,
            f"{item.epss.score:.4f}" if item.epss else "",
            f"{item.epss.percentile:.4f}" if item.epss else "",
            "YES" if item.is_kev else "NO",
            "YES" if item.has_poc else "NO",
            item.metrics.attack_vector if (item.metrics and item.metrics.attack_vector) else "",
            item.metrics.privileges_required if (item.metrics and item.metrics.privileges_required) else "",
            item.published_date[:10] if item.published_date else "",
            "; ".join(item.cwe_ids),
            item.description,
        ])

    return output.getvalue()


def to_markdown(items: List[CVEItem], query_title: str = "") -> str:
    """Exports CVEItems into GitHub Flavored Markdown."""
    lines = []
    lines.append(f"# VulnHound Threat Intelligence Report")
    if query_title:
        lines.append(f"**Query / Scope:** `{query_title}`\n")

    lines.append(f"| CVSS | Severity | EPSS | KEV | PoC | CVE ID | Published | CWE | Description |")
    lines.append(f"| :---: | :---: | :---: | :---: | :---: | :--- | :---: | :--- | :--- |")

    for item in items:
        score = f"{item.cvss_score:.1f}" if item.cvss_score is not None else "N/A"
        epss = f"{item.epss.percentage_str}" if item.epss else "-"
        kev = "🚨 **YES**" if item.is_kev else "No"
        poc = "🔥 **YES**" if item.has_poc else "No"
        desc = html.escape(item.description.replace("\n", " ").replace("|", "\\|"))
        if len(desc) > 120:
            desc = desc[:117] + "..."
        cwes = ", ".join(item.cwe_ids) if item.cwe_ids else "-"
        pdate = item.published_date[:10] if item.published_date else "-"

        lines.append(
            f"| **{score}** | {item.severity} | {epss} | {kev} | {poc} | [`{item.id}`](https://nvd.nist.gov/vuln/detail/{item.id}) | {pdate} | {cwes} | {desc} |"
        )

    lines.append(f"\n*Generated by VulnHound Advanced - Found {len(items)} vulnerabilities.*")
    return "\n".join(lines)


def to_html(items: List[CVEItem], query_title: str = "") -> str:
    """
    Generates a sleek, interactive cyber threat intelligence dashboard in HTML.
    Includes client-side instant search, category filters, and dark mode styling.
    """
    total = len(items)
    critical_count = sum(1 for x in items if x.severity == "CRITICAL")
    kev_count = sum(1 for x in items if x.is_kev)
    poc_count = sum(1 for x in items if x.has_poc)

    rows_html = []
    for item in items:
        score = item.cvss_score
        score_display = f"{score:.1f}" if score is not None else "N/A"
        sev_class = item.severity.lower()

        epss_display = f"{item.epss.score * 100:.1f}%" if item.epss else "-"
        epss_bar = int(item.epss.score * 100) if item.epss else 0

        kev_badge = '<span class="badge badge-kev">KEV ACTIVE</span>' if item.is_kev else '<span class="text-muted">-</span>'
        poc_badge = f'<span class="badge badge-poc">PoC ({len(item.pocs)})</span>' if item.has_poc else '<span class="text-muted">-</span>'

        pocs_json = html.escape(json.dumps([p.url for p in item.pocs]))

        rows_html.append(f"""
        <tr data-cve="{item.id}" data-severity="{item.severity}" data-kev="{str(item.is_kev).lower()}" data-poc="{str(item.has_poc).lower()}">
            <td><span class="badge badge-{sev_class}">{score_display}</span></td>
            <td><strong>{item.severity}</strong></td>
            <td>
                <div class="epss-bar-container" title="{epss_display}">
                    <div class="epss-bar" style="width: {epss_bar}%;"></div>
                    <span>{epss_display}</span>
                </div>
            </td>
            <td>{kev_badge}</td>
            <td>{poc_badge}</td>
            <td><a href="https://nvd.nist.gov/vuln/detail/{item.id}" target="_blank" class="cve-link"><strong>{item.id}</strong></a></td>
            <td><span class="text-muted">{item.published_date[:10]}</span></td>
            <td class="desc-cell">{html.escape(item.description)}</td>
        </tr>
        """)

    html_template = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>VulnHound Threat Intelligence Report</title>
    <style>
        :root {{
            --bg-primary: #0a0e14;
            --bg-secondary: #131924;
            --bg-card: #1c2434;
            --text-primary: #e6edf3;
            --text-muted: #8b949e;
            --border-color: #30363d;
            --color-critical: #ff4d4d;
            --color-high: #ff944d;
            --color-medium: #ffd152;
            --color-low: #3dd68c;
            --color-cyan: #38ef7d;
            --color-purple: #b388ff;
        }}
        * {{ box-sizing: border-box; margin: 0; padding: 0; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, monospace; }}
        body {{ background-color: var(--bg-primary); color: var(--text-primary); padding: 24px; }}
        .header {{ margin-bottom: 24px; border-bottom: 1px solid var(--border-color); padding-bottom: 16px; }}
        .header h1 {{ font-size: 24px; color: #58a6ff; display: flex; align-items: center; gap: 8px; }}
        .header .subtitle {{ color: var(--text-muted); font-size: 14px; margin-top: 4px; }}
        .stats-grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); gap: 16px; margin-bottom: 24px; }}
        .stat-card {{ background: var(--bg-secondary); border: 1px solid var(--border-color); border-radius: 8px; padding: 16px; text-align: center; }}
        .stat-val {{ font-size: 28px; font-weight: bold; margin-top: 4px; }}
        .stat-val.critical {{ color: var(--color-critical); }}
        .stat-val.kev {{ color: #ff5252; }}
        .stat-val.poc {{ color: var(--color-purple); }}
        .stat-val.total {{ color: #58a6ff; }}
        .controls {{ display: flex; gap: 12px; margin-bottom: 16px; flex-wrap: wrap; }}
        .search-box {{ flex-grow: 1; min-width: 250px; }}
        .search-box input {{ width: 100%; padding: 10px 14px; background: var(--bg-secondary); border: 1px solid var(--border-color); border-radius: 6px; color: #fff; font-size: 14px; outline: none; }}
        .filter-btn {{ padding: 8px 14px; background: var(--bg-secondary); border: 1px solid var(--border-color); border-radius: 6px; color: var(--text-primary); cursor: pointer; font-size: 13px; }}
        .filter-btn.active {{ background: #1f6feb; border-color: #388bfd; font-weight: bold; }}
        .table-container {{ overflow-x: auto; background: var(--bg-secondary); border: 1px solid var(--border-color); border-radius: 8px; }}
        table {{ width: 100%; border-collapse: collapse; text-align: left; font-size: 13px; }}
        th, td {{ padding: 12px 14px; border-bottom: 1px solid var(--border-color); vertical-align: top; }}
        th {{ background: #161b22; color: var(--text-muted); font-weight: 600; text-transform: uppercase; font-size: 11px; letter-spacing: 0.5px; }}
        tr:hover {{ background-color: rgba(255, 255, 255, 0.03); }}
        .cve-link {{ color: #58a6ff; text-decoration: none; }}
        .cve-link:hover {{ text-decoration: underline; }}
        .badge {{ display: inline-block; padding: 3px 7px; border-radius: 4px; font-size: 11px; font-weight: bold; text-align: center; }}
        .badge-critical {{ background: rgba(255, 77, 77, 0.2); color: var(--color-critical); border: 1px solid var(--color-critical); }}
        .badge-high {{ background: rgba(255, 148, 77, 0.2); color: var(--color-high); border: 1px solid var(--color-high); }}
        .badge-medium {{ background: rgba(255, 209, 82, 0.2); color: var(--color-medium); border: 1px solid var(--color-medium); }}
        .badge-low {{ background: rgba(61, 214, 140, 0.2); color: var(--color-low); border: 1px solid var(--color-low); }}
        .badge-kev {{ background: #d32f2f; color: #fff; font-weight: bold; }}
        .badge-poc {{ background: rgba(179, 136, 255, 0.2); color: var(--color-purple); border: 1px solid var(--color-purple); }}
        .text-muted {{ color: var(--text-muted); }}
        .desc-cell {{ max-width: 480px; line-height: 1.4; }}
        .epss-bar-container {{ width: 80px; height: 16px; background: #21262d; border-radius: 8px; position: relative; overflow: hidden; display: flex; align-items: center; }}
        .epss-bar {{ height: 100%; background: #388bfd; position: absolute; left: 0; top: 0; }}
        .epss-bar-container span {{ position: relative; z-index: 1; font-size: 10px; width: 100%; text-align: center; font-weight: bold; text-shadow: 0 0 2px #000; }}
    </style>
</head>
<body>
    <div class="header">
        <h1>🔍 VulnHound Advanced Threat Dossier</h1>
        <div class="subtitle">Scope / Query: <strong>{html.escape(query_title or 'All Results')}</strong> | Enriched with NVD 2.0, FIRST EPSS &amp; CISA KEV</div>
    </div>

    <div class="stats-grid">
        <div class="stat-card">
            <div class="text-muted">Total CVEs</div>
            <div class="stat-val total">{total}</div>
        </div>
        <div class="stat-card">
            <div class="text-muted">Critical Severity</div>
            <div class="stat-val critical">{critical_count}</div>
        </div>
        <div class="stat-card">
            <div class="text-muted">CISA KEV (In Wild)</div>
            <div class="stat-val kev">{kev_count}</div>
        </div>
        <div class="stat-card">
            <div class="text-muted">Discovered PoCs</div>
            <div class="stat-val poc">{poc_count}</div>
        </div>
    </div>

    <div class="controls">
        <div class="search-box">
            <input type="text" id="filterInput" placeholder="Filter in results (CVE, keyword, software, etc)..." onkeyup="filterTable()">
        </div>
        <button class="filter-btn active" onclick="applyPreset('all', this)">All ({total})</button>
        <button class="filter-btn" onclick="applyPreset('critical', this)">Critical ({critical_count})</button>
        <button class="filter-btn" onclick="applyPreset('kev', this)">CISA KEV ({kev_count})</button>
        <button class="filter-btn" onclick="applyPreset('poc', this)">Has PoC ({poc_count})</button>
    </div>

    <div class="table-container">
        <table id="cveTable">
            <thead>
                <tr>
                    <th>CVSS</th>
                    <th>Severity</th>
                    <th>EPSS</th>
                    <th>KEV</th>
                    <th>PoC</th>
                    <th>CVE ID</th>
                    <th>Published</th>
                    <th>Description</th>
                </tr>
            </thead>
            <tbody>
                {''.join(rows_html)}
            </tbody>
        </table>
    </div>

    <script>
        let currentPreset = 'all';

        function applyPreset(preset, btn) {{
            currentPreset = preset;
            document.querySelectorAll('.filter-btn').forEach(b => b.classList.remove('active'));
            btn.classList.add('active');
            filterTable();
        }}

        function filterTable() {{
            const search = document.getElementById('filterInput').value.toLowerCase();
            const rows = document.querySelectorAll('#cveTable tbody tr');

            rows.forEach(row => {{
                const text = row.innerText.toLowerCase();
                const sev = row.getAttribute('data-severity');
                const isKev = row.getAttribute('data-kev') === 'true';
                const hasPoc = row.getAttribute('data-poc') === 'true';

                let matchesPreset = true;
                if (currentPreset === 'critical') matchesPreset = (sev === 'CRITICAL');
                else if (currentPreset === 'kev') matchesPreset = isKev;
                else if (currentPreset === 'poc') matchesPreset = hasPoc;

                const matchesSearch = text.includes(search);

                if (matchesPreset && matchesSearch) {{
                    row.style.display = '';
                }} else {{
                    row.style.display = 'none';
                }}
            }});
        }}
    </script>
</body>
</html>
"""
    return html_template
